enableWorkspaceDiagnostics = true

[adapterCommand.rust]
path = "testing-ls-adapter"
extra_arg = [
  "--test-kind=cargo-test",
  "--workspace"
]
include = [
  "/**/*.rs"
]
exclude = [
  "/demo/**/*"
]
workspace_dir = "."
