[language-server.testing-ls]
command = "testing-language-server"
args = []

[[language]]
name = "rust"
language-servers = [ { name = "testing-ls", only-features = [ "diagnostics" ] }, "rust-analyzer" ]

[[language]]
name = "typescript"
language-servers = [ { name = "testing-ls", only-features = [ "diagnostics" ] }, "typescript-language-server" ]

[[language]]
name = "php"
language-servers = [ { name = "testing-ls", only-features = [ "diagnostics" ] }, "phpactor" ]

[[language]]
name = "go"
language-servers = [ { name = "testing-ls", only-features = [ "diagnostics" ] }, "gopls" ]

[[language]]
name = "javascript"
language-servers = [ { name = "testing-ls", only-features = [ "diagnostics" ] }, "typescript-language-server" ]