name: Release

on:
  push:
    tags:
      - 'adapter-v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates/adapter

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build project
      run: cargo build --release

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --token $CARGO_REGISTRY_TOKEN
